name: 'Update CHANGELOG - v1'
on: workflow_dispatch
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    
      # Checkout project repository
      - name: Checkout
        uses: actions/checkout@v3
      
      # Setup Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          registry-url: https://registry.npmjs.org/
          node-version: '14'

      - name: Cache node modules
        id: cache-nodemodules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          # caching node_modules
          path: node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      
      - name: Install Dependencies
        if: steps.cache-nodemodules.outputs.cache-hit != 'true'
        run: |
          npm ci
      
      # Configure Git
      - name: Git configuration
        run: |
          git config --global user.email "felipe.so.dev@gmail.com"
          git config --global user.name "GitHub Actions"
      
      # Configura changelog
      - name: Changelog configuration
        run: |
          git log --online
          npm install -g auto-changelog
          auto-changelog -p --template changelog-template.hbs --commit-limit false && git add CHANGELOG.md
          npm run version-json
      
      # Push repository changes
      - name: Push changes to repository
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
        run: |
          git push origin
