name: 'Release package - v1'
on:
  workflow_dispatch:
    inputs:
      release-type:
        description: 'Release type (one of): patch, minor, major'
        required: true
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    
      # Checkout project repository
      - name: Checkout
        uses: actions/checkout@v3

      # Setup Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          registry-url: https://registry.npmjs.org/
          node-version: '14'

      - name: Cache node modules
        id: cache-nodemodules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          # caching node_modules
          path: node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      
      - name: Install Dependencies
        if: steps.cache-nodemodules.outputs.cache-hit != 'true'
        run: |
          npm ci

      # Configure Git
      - name: Git configuration
        run: |
          git config --global user.email "felipe.so.dev@gmail.com"
          git config --global user.name "felipe-frade"
          
      # Configure Git
      - name: Release
        run: |
          npm version ${{ github.event.inputs.release-type }}

      # Push repository changes
      - name: Push changes to repository
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
        run: |
          git push origin
      
      # Create Pull Request
      - name: Run the Action
      uses: devops-infra/action-pull-request@v0.5.5
      with:
        github_token: ${{ secrets.MY_TOKEN }}
        source_branch: release
        target_branch: main
        title: My pull request
        # template: .github/PULL_REQUEST_TEMPLATE.md
        body: "**Automated pull request**"
        reviewer: octocat
        assignee: octocat
        label: enhancement
        milestone: My milestone
        draft: true
        old_string: "<!-- Add your description here -->"
        new_string: "** Automatic pull request**"
        get_diff: true
        ignore_users: "dependabot"
        allow_no_diff: false
